# Generated by Django 5.2.8 on 2025-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locate', models.IntegerField(choices=[(1, 'Fila 1'), (2, 'Fila 2'), (3, 'Fila 3'), (4, 'En Ruma')])),
                ('nro_team', models.IntegerField(max_length=11, unique=True)),
                ('type', models.CharField(max_length=4)),
                ('line', models.CharField(max_length=4)),
                ('type_load', models.CharField(max_length=20)),
                ('deposit_days', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Team Status',
            },
        ),
    ]
