# Generated by Django 5.2.8 on 2025-11-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_equipo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_status',
            name='nro_team',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
