# Generated by Django 5.2.8 on 2025-11-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_equipo_status_locate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_status',
            name='locate',
            field=models.IntegerField(choices=[(1, 'Fila 1'), (2, 'Fila 2'), (3, 'Fila 3'), (4, 'En Ruma')]),
        ),
    ]
